# Generated by Django 2.2 on 2020-02-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.FileField(upload_to='')),
                ('txt_name', models.CharField(max_length=200, null=True)),
                ('txt_title', models.CharField(max_length=250, null=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_lemma_extracted', models.BooleanField(default=False)),
            ],
        ),
    ]
