# Generated by Django 2.2 on 2020-02-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saatTempApp', '0002_sentences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('section_number', models.CharField(max_length=50, null=True)),
                ('is_heading', models.BooleanField(default=False)),
                ('txt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saatTempApp.Text_files')),
            ],
        ),
    ]
